# Generated by Django 5.1.1 on 2024-11-30 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_address_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
