# Generated by Django 5.1.1 on 2024-12-02 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_imagemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='address',
        ),
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.ManyToManyField(to='book.address'),
        ),
    ]
