# Generated by Django 5.1.1 on 2024-12-02 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_remove_student_address_student_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='address',
            new_name='addresses',
        ),
    ]
